### ISSUE TITLE
Request to add guidance for competitor's source 

### ISSUE THREAD

**Issue by salander0411** [awslabs/aws-data-replication-hub#13]
No documentation for those who are using Ali OSS. For example, how to configure the credential for OSS/tencert/Qiniu ？

**Comment by JoeShi** [comment]
Hi, all competitor configurations are the same. Just input AK/SK in Parameter Store. https://aws-crm.lightning.force.com/lightning/r/Opportunity/0064z000024pMA0AAM/view
