### ISSUE TITLE
Can not run the cloudformation in AWS China cn-north-1 region

### ISSUE THREAD

**Issue by Robin021** [awslabs/aws-data-replication-hub#17]
Dear,
Does anyone encounter the below issue when using the cloudformation to deployment? 

`Template format error: Unrecognized resource types: [AWS::Cognito::UserPool, AWS::Cognito::UserPoolDomain, AWS::Cognito::UserPoolUser, AWS::Cognito::UserPoolClient]`
When I try to use the designer, there is no Cognito type at the left navigation, what should I do if I want to run this in AWS China region?  

Many Thanks !

**Comment by JoeShi** [comment]
Hello. If you are trying to replicate S3 data in AWS CN region. please go ahead with the [S3 Plugin](https://github.com/awslabs/amazon-s3-data-replication-hub-plugin). The UI portal cannot be deployed in China regions now. This feature will be included in next major release.

**Comment by JoeShi** [comment]
Please use the CloudFormation launch button in `For China Partition`.

**Comment by Robin021** [comment]
Hi JoeShi,
This helps a lot. Thanks.
