### ISSUE TITLE
Request to add support for migrating from google cloud storage to aws s3

### ISSUE THREAD

**Issue by yueliang9527** [awslabs/aws-data-replication-hub#26]
Hi,

please add plugin to support migrate google cloud storage  to aws s3 .

**Comment by JoeShi** [comment]
Thanks. Yue Liang. We have added this feature in the plugin. https://github.com/awslabs/amazon-s3-data-replication-hub-plugin. You can use the plugin directly without the user interface. 

The update to the user interface will also be included in the next release.

**Comment by JoeShi** [comment]
Hi, we have launched this feature. This feature can only be used AWS Global regions. Please create another issue if you need further help.
