### ISSUE TITLE
denied by S3

### ISSUE THREAD

**Issue by DevOpserzhao** [awslabs/aws-data-replication-hub#27]
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for aws-gcr-solutions-us-east-1/Aws-data-replication-component-s3/v1.0.1/assetd379814670287d98ddcacc8ae32b59e34c2fa89abb79440223d899bdfadfda4c.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 95347991-4765-431c-b19d-ddc8f028ef06)

**Comment by daixba** [comment]
@DevOpserzhao Thanks for raising the issue, We have resolved the bug, please can you try again. You will need to delete the stack of Data Replication Hub and redeploy Hub again, then you can create S3 replication Task.  Sorry for the trouble.

**Comment by JoeShi** [comment]
Close issue, please create another one there if there is more error.
