### ISSUE TITLE
Global S3 synchronizes data to CN S3 failure

### ISSUE THREAD

**Issue by ls-2018** [awslabs/aws-data-replication-hub#28]
The premise：
source
- account: A 
- bucket :s3-sync-ls-source 
- region: ap-southeast-1

target 
- account: B
- bucket: s3sync-ls-target  
- aksk 
- region: cn-northwest-1

When I start the DataReplicationHub stack in my A account, and create A S3 task, here are the task parameters
![image](https://user-images.githubusercontent.com/38821215/103261977-76d26780-49de-11eb-8e13-af9f35a40784.png)
Then I change the ECS trigger time to 5 minutes, and it always stops by itself. And I don't need to see synchronized data in the target bucket
![image](https://user-images.githubusercontent.com/38821215/103262107-e6e0ed80-49de-11eb-88f4-28d6a4861f74.png)
But I would have no problem using the S3 plug-in alone。
Could you help me solve the problem？

**Comment by JoeShi** [comment]
taking a look

**Comment by JoeShi** [comment]
Hi, can you share the log of the ECS Fargate container?

**Comment by ls-2018** [comment]
Ok, let me see

**Comment by ls-2018** [comment]
I can't find the log. I'll share the screen.

会议时间：2020/12/29 15:27-16:27
点击链接直接加入会议：
https://meeting.tencent.com/s/Zpt4qv4J79UC
会议 ID：601 376 413

**Comment by ls-2018** [comment]
你能来么？

**Comment by ls-2018** [comment]
The problem has been solved。
![image](https://user-images.githubusercontent.com/38821215/103268395-53afb400-49ee-11eb-9771-e02178dde818.png)
Solutions:
   There are three items in the Parameter Store
  {
    "access_key_id": "",
    "secret_access_key": "",
    "region_name":"cn-northwest-1"
  }

**Comment by JoeShi** [comment]
Thanks. Will close this issue.
