### ISSUE TITLE
How to troubleshoot if data is not synchronized to s3

### ISSUE THREAD

**Issue by DevOpserzhao** [awslabs/aws-data-replication-hub#29]
How to troubleshoot if data is not synchronized to s3

 
Source is qiniu
Destination  is global aws s3

**Comment by DevOpserzhao** [comment]
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3-as0.qiniucs.com/testzxf?list-type=2&max-keys=1000&prefix=&encoding-type=url"

**Comment by daixba** [comment]
@DevOpserzhao  Did you put region_name in the credentials parameter?  If yes, what is the value?

Basically, we are expecting the endpoint url for Qiniu is like https://s3-{region_name}.qiniucs.com,  and it seems that the region name is as0 in your case? but it should be one of below values
- cn-east-1
- cn-north-1
- cn-south-1
-  us-north-1
 - ap-southeast-1

Please refer to https://developer.qiniu.com/kodo/4088/s3-access-domainname for more details.

Thanks.

**Comment by JoeShi** [comment]
Hi, @DevOpserzhao We have recently released a new update. You don't have to specify the region name in the Parameter Store anymore. Now you can select the region name from the Web UI.

Please try and let us known if it works for you.

**Comment by JoeShi** [comment]
Close due to inative issue. Please create another issue if need further help
