### ISSUE TITLE
Parameter Store保存的凭证参数没有同步到AwsDataReplicationHub

### ISSUE THREAD

**Issue by Ganvor1124** [awslabs/aws-data-replication-hub#30]
部署AwsDataReplicationHub后创建任务，发现没有OSS凭证，然后往Parameter Store添加凭证参数，AwsDataReplicationHub中无法出凭证参数
![image](https://user-images.githubusercontent.com/76504701/103871657-50ac7600-5108-11eb-97ff-e5491953fa98.png)

**Comment by JoeShi** [comment]
您好，帮忙确认一下：
1. 您的 Parameter Store 和这个解决方案部署在同一个AWS region吗？

**Comment by Ganvor1124** [comment]
> 您好，帮忙确认一下：
> 
> 1. 您的 Parameter Store 和这个解决方案部署在同一个AWS region吗？

是在一个区域，都是us-east-1。我在CloudFormation创建DataReplicationHub时，除了输入AdminEmail外，没有填写其他的信息，不知道是不是和这个有关，比如是不是要配置IAM？但是据了解，我操作的这个AWS账号是有管理员权限的

**Comment by JoeShi** [comment]
请问您配置 Parameter Store 的时候选择是类型是 `SecureString ` 么？


![Screen Shot 2021-01-07 at 9 27 52 PM](https://user-images.githubusercontent.com/2173635/103897972-38038680-512f-11eb-9893-7e77d9649704.png)

如果选择的是 `SecureString` 类型么？

**Comment by Ganvor1124** [comment]
之前选择的是text，改成SecureString后可以了。

**Comment by JoeShi** [comment]
OK。如果还有其他问题欢迎继续开issue.

**Comment by Ganvor1124** [comment]
我这边还有比较多使用上的问题，我们这边希望寻求一个应用到生产的迁移方案。数据量大概在1.4TB，从海外OSS迁移到海外S3，能否提供更便利的咨询方式？还是继续使用issue方式？

**Comment by JoeShi** [comment]
可以提供便利的咨询方案，我们可以视频会议。麻烦发邮件到 qiaoshi@amazon.com， 并提供12位 AWS 账号。我会帮忙联系AWS 解决方案架构师提供咨询。
