### ISSUE TITLE
Suggest replication hub support VPC mode which can let customer leverage the direct connect to do transfer

### ISSUE THREAD

**Issue by liangruibupt** [awslabs/aws-data-replication-hub#32]
Make the task can running within VPC which already setup the direct connect. So it can more stable and faster than public internet

**Comment by JoeShi** [comment]
Yes. we are currently working on a new version of Data Replicaiton Hub. The new version will transfer data through EC2 Graviton2 with BBR enabled. The new version will also support VPC configuration.

ETA 3/15/2021

**Comment by liangruibupt** [comment]
Verified the VPC configuration and EC2 Graviton2 with BBR enabled already supported in v2 edition
