### ISSUE TITLE
Can not get the task list

### ISSUE THREAD

**Issue by Robin021** [awslabs/aws-data-replication-hub#36]
always loading but without result. 
where should i trouble shoting please?

**Comment by daixba** [comment]
Can you please provide more details on the issue, for example:  Did you deploy the latest version ? Which region did you deploy the solution to? what is always loading?  Can you check if the cloudformation stacks are created successfully?  etc.

**Comment by Robin021** [comment]
Dear,
The version is :  Template version v1.2.1 
Region: cn-north-1
Stack create successfully: 
![image](https://user-images.githubusercontent.com/22043214/112974630-4341dd80-9185-11eb-8558-db5317c793a3.png)

The loading status: 
![image](https://user-images.githubusercontent.com/22043214/112974806-73897c00-9185-11eb-8667-3fa19c974c05.png)

**Comment by daixba** [comment]
@Robin021 Have you started any S3 replication tasks?  If yes, you can check the cloudformation stack, there should be one with stack name including 'S3'. Can you check the status of that one.

This looks like a UI problem, the task list comes from a DynamoDB provisioned once you deployed this solution.  But I think the s3 replication task is what matters,  so if you have started the task but nothing happens, you can check the ECS cluster, there is one with name 'Hub' included. You can go to the Task tab, check the stopped task, click the latest one and check the log of the ECS task.  Also, you can go to Cloudwatch dashboard, check the replication progress.

**Comment by Robin021** [comment]
@daixba Thanks for the reply. 
This happends at the first initial setup. none task created. 
As your information i checked the ECS but seems the cluster created with empty , no task and no service :
![image](https://user-images.githubusercontent.com/22043214/118075405-888f3700-b3e2-11eb-81ab-0b15f4189485.png)

**Comment by Robin021** [comment]
It is caused by my mistake : 
OIDC provider should end with  https://123.authing.cn/oidc/
