### ISSUE TITLE
improve project dependency management

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-data-replication-hub#4]
The readme of project requires the explicit dependency to `CDK 1.64.1`. It’s really redundant for end users to install a particular cdk version, installing it might conflict with the existing cdk in user’s system.

You might improve the dependency management via,

1. pin cdk version via package.json and lock file of dependency tool, such as npm/yarn
1. update the doc to how install dependencies
1. update `cdk` command in doc to `npx cdk` that will use the expected cdk managed by project
1. remove `cdk` from prerequisites of doc

**Comment by JoeShi** [comment]
thanks for the suggestion, will fix in next version

**Comment by JoeShi** [comment]
resolved. changed to use 'npx'
